---
- name: Deploy Java Application
  hosts: 127.0.0.1         #target_servers
  become: true

  vars:
    java_app_name: "HelloWorldApp"   # your-java-app
    java_app_version: "1.0.0"
    java_app_jar: "{{ java_app_name }}-{{ java_app_version }}.jar"
    java_app_download_url: "/home/ubuntu/ansible/{{ java_app_jar }}"     #"file:///path/to/files/{{ java_app_jar }}"
    java_app_target_directory: "/opt/{{ java_app_name }}"
    app_service_name: "hello-world-service" # "your-app-service"

  tasks:
    - name: Install Java
      apt:
        name: openjdk-11-jdk
        state: present

    - name: Create Application Directory
      file:
        path: "{{ java_app_target_directory }}"
        state: directory

    - name: If follow=yes, /home/ubuntu/ansible/javansible will be overwritten by contents of foo.conf
      ansible.builtin.copy:
            src: /home/ubuntu/ansible/HelloWorldApp.java
            dest: /home/ubuntu/ansible/javansible  # link to /path/to/file

    - name: Restart App Service
      systemd:
      name: "{{ app_service_name }}"
      state: restarted

